version: "3.5"
services:
  gameplay-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      SERVICE_4200_NAME: GamePlay
    volumes:
      - ".:/GamePlay/usr/src/app"
      - /GamePlay/usr/src/app/node_modules
    networks:
      - gameplay-network
networks:
  gameplay-network:
    name: quizrt-network
    external: true
